const Strings = {
	reserve: 'Reservas',
	reserveDescription: 'Confira suas reservas! ',
	add: 'Incluir',
	balancete: 'Balancete',
	balanceteDescription: 'Confira seus balancetes',
	balanceteDetalhe: 'Detalhe Balancete',
	balanceteDetalheDescription: 'Confira os detalhes do seu balancete',
	despesasDiversas: 'Despesas diversas',
	honorariosSindico: 'Honorários de síndico',
	luzForca: 'Luz e Força',
	balanceteDetails: 'Ver detalhes',
	publication: 'Publicações',
	publicationDescription: 'Confira a lista de publicações',
	tickets: 'Boletos',
	ticketsDescription: 'Confira sua lista de boletos',
	ticketDetails: 'Boleto',
	ticketDetailsDescription: 'Confira os detalhes do boleto',
	reserveAdd: 'Criação da reserva',
	selectReserveAmbient: 'Selecione o ambiente que deseja reservar',
	selectDayOnCalendar: 'Selecione  a data no calendário para',
	area: 'Área',
	capacitySit: 'Capacidade pessoas sentadas:',
	capacityFoot: 'Capacidade pessoas em pé:',
	typeAmbient: 'Tipo ambiente:',
	usageFee: 'Taxa de uso:',
	schedulingUntil: 'Agendamento até:',
	cancelUntil: 'Cancelamento até:',
	limitAmbient: 'Ambiente permite:',
	continue: 'Continuar',
	selectHour: 'Selecione um horário ',
	date: 'Data:',
	checkDataReserve: 'Confirme os dados da sua reserva',
	period: 'Período',
	to: 'às',
	rulesOfUse: 'Regras de Uso',
	readAndAgree: 'Li e Concordo',
	confirmReservation: 'Confirmar a Reserva',
	cancelReservation: 'Cancelar a Reserva',
	home: 'Bom dia',
	homeUser: 'Natan',
	homeDescription: 'Condomínio Vila Real ',
	condominiumExchange: 'Trocar Condomínio Preferencial',
	enter: 'Entrar',
	noAcont: 'Não tenho uma conta',
};

export default Strings;
