const Strings = {
	reserve: 'Reservas',
	reserveDescription: 'Confira suas reservas! ',
	add: 'Incluir',
	reserveAdd: 'Criação da reserva',
	selectReserveAmbient: 'Selecione o ambiente que deseja reservar',
	selectDayOnCalendar: 'Selecione  a data no calendário para',
	area: 'Área',
	capacitySit: 'Capacidade pessoas sentadas:',
	capacityFoot: 'Capacidade pessoas em pé:',
	typeAmbient: 'Tipo ambiente:',
	usageFee: 'Taxa de uso:',
	schedulingUntil: 'Agendamento até:',
	cancelUntil: 'Cancelamento até:',
	limitAmbient: 'Ambiente permite:',
	continue: 'Continuar',
	selectHour: 'Selecione um horário ',
	date: 'Data:',
	checkDataReserve: 'Confirme os dados da sua reserva',
	period: 'Período',
	to: 'às',
	rulesOfUse: 'Regras de Uso',
	readAndAgree: 'Li e Concordo',
	confirmReservation: 'Confirmar a reserva',
	cancelReservation: 'Cancelar a reserva',
	cancellationReserve: 'Cancelamento da reserva',
	confirmCancellation: 'Confirme o cancelamento',
	confirm: 'Confirmar',
	close: 'Fechar',
	reason: 'Motivo',
	reservesManagement: 'Gestão das Reservas',
	confirmDeleteReserve: 'Você confirma a exclusão da reserva?',
	yes: 'Sim',
	no: 'Não',
	confirmationReserve: 'Confirmação da reserva',
	pendencies: 'Pendências',
};

export default Strings;
